name: CI/CD para Task Manager

on:
  push:
    branches:
      - main  # Se ejecuta en cada push a main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: 🔧 Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar dependencias y construir el proyecto
        run: ./mvnw clean package -DskipTests  # Se omiten pruebas mientrass se implementan

  deploy:
    needs: build  # Se ejecuta solo si la compilación fue exitosa
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: 🔧 Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Desplegar en Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          railway up --service task-manager
